steps:
  # Step 1: Install Node.js dependencies (with cache)
  - name: 'node:20'
    dir: 'rentman-app'
    entrypoint: 'npm'
    args: ['install', '--force', '--prefer-offline']

  # Step 2: Generate Android project with Expo
  - name: 'node:20'
    dir: 'rentman-app'
    entrypoint: 'npx'
    args: ['expo', 'prebuild', '--platform', 'android', '--clean']

  # Step 3: Copy keystore into android/app
  - name: 'ubuntu'
    dir: 'rentman-app'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'cp rentman.keystore android/app/'

  # Step 4: Build Android APK - OPTIMIZED VERSION
  - name: 'ghcr.io/cirruslabs/android-sdk:34'
    dir: 'rentman-app/android'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== CONFIGURACIÓN OPTIMIZADA ==="
        
        # Install Node.js 20
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - > /dev/null 2>&1
        apt-get install -y nodejs > /dev/null 2>&1
        
        # Configure Gradle for speed
        cat >> gradle.properties <<EOF
        
        # Architecture: Solo ARM64 (reduce 75% del tiempo de compilación)
        reactNativeArchitectures=arm64-v8a
        
        # Memory optimization
        org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
        org.gradle.daemon=false
        org.gradle.parallel=true
        org.gradle.configureondemand=true
        org.gradle.caching=true
        
        # React Native optimizations
        org.gradle.workers.max=4
        
        # Disable unnecessary tasks
        android.enableR8.fullMode=false
        android.enableJetifier=false
        EOF
        
        echo "=== INICIANDO BUILD OPTIMIZADO ==="
        chmod +x gradlew
        sed -i 's/\r$//' gradlew
        
        # Build con optimizaciones
        ./gradlew assembleRelease \
          --no-daemon \
          --parallel \
          --max-workers=4 \
          --build-cache \
          --configure-on-demand \
          --stacktrace \
          -x lintVitalAnalyzeRelease \
          -x lintVitalReportRelease

  # Step 5: Copy APK to output bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TIMESTAMP=$$(date +%Y%m%d-%H%M%S)
        APK_PATH="/workspace/rentman-app/android/app/build/outputs/apk/release/app-release.apk"
        
        if [ -f "$$APK_PATH" ]; then
          gsutil cp "$$APK_PATH" "gs://rentman-builds/app-release-$${TIMESTAMP}.apk"
          echo "APK uploaded to: gs://rentman-builds/app-release-$${TIMESTAMP}.apk"
          
          gsutil cp "$$APK_PATH" "gs://rentman-builds/app-release-latest.apk"
          echo "Latest APK: gs://rentman-builds/app-release-latest.apk"
        else
          echo "APK not found at $$APK_PATH"
          exit 1
        fi

options:
  logging: GCS_ONLY
  machineType: 'E2_HIGHCPU_32'  # Máquina 4x más potente
  diskSizeGb: 50
  
logsBucket: 'gs://rentman-builds'

timeout: '3600s'
