steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    dir: 'rentman-v2'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps']

  # Step 2: Generate Android project
  - name: 'node:20'
    dir: 'rentman-v2'
    entrypoint: 'npx'
    args: ['expo', 'prebuild', '--platform', 'android', '--clean']

  # Step 3: Copy keystore (si existe)
  - name: 'ubuntu'
    dir: 'rentman-v2'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f "../rentman-app/rentman.keystore" ]; then
          cp ../rentman-app/rentman.keystore android/app/
          echo "✅ Keystore copiado"
        else
          echo "⚠️  Keystore no encontrado, usando debug"
        fi

  # Step 4: Build APK
  - name: 'ghcr.io/cirruslabs/android-sdk:34'
    dir: 'rentman-v2/android'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== CONFIGURANDO BUILD ==="
        
        # Install Node.js
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - > /dev/null 2>&1
        apt-get install -y nodejs > /dev/null 2>&1
        
        # Configure Gradle
        echo "" >> gradle.properties
        echo "# Build optimizations" >> gradle.properties
        echo "reactNativeArchitectures=arm64-v8a" >> gradle.properties
        echo "org.gradle.jvmargs=-Xmx4096m" >> gradle.properties
        echo "org.gradle.daemon=false" >> gradle.properties
        echo "org.gradle.parallel=true" >> gradle.properties
        echo "org.gradle.caching=true" >> gradle.properties
        echo "org.gradle.workers.max=4" >> gradle.properties
        echo "android.enableR8.fullMode=false" >> gradle.properties
        echo "android.enableJetifier=false" >> gradle.properties
        echo "org.gradle.java.installations.auto-download=false" >> gradle.properties
        
        echo "=== BUILDING APK ==="
        chmod +x gradlew
        sed -i 's/\r$//' gradlew
        
        ./gradlew assembleRelease \
          --no-daemon \
          --parallel \
          --max-workers=4 \
          --build-cache \
          --stacktrace \
          -x lint \
          -x lintVitalAnalyzeRelease \
          -x lintVitalRelease \
          -x lintVitalReportRelease

  # Step 5: Upload APK
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TIMESTAMP=$$(date +%Y%m%d-%H%M%S)
        APK_PATH="/workspace/rentman-v2/android/app/build/outputs/apk/release/app-release.apk"
        
        if [ -f "$$APK_PATH" ]; then
          gsutil cp "$$APK_PATH" "gs://rentman-builds/rentman-v2-$${TIMESTAMP}.apk"
          gsutil cp "$$APK_PATH" "gs://rentman-builds/rentman-v2-latest.apk"
          echo "✅ APK uploaded: gs://rentman-builds/rentman-v2-latest.apk"
        else
          echo "❌ APK not found"
          exit 1
        fi

options:
  logging: GCS_ONLY
  machineType: 'E2_HIGHCPU_32'
  
logsBucket: 'gs://rentman-builds'
timeout: '3600s'
