steps:
  # Step 1: Install Node.js dependencies (CLEAN INSTALL)
  - name: 'node:20'
    dir: 'rentman-app'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== CLEAN INSTALL ==="
        rm -rf node_modules
        rm -rf .expo
        rm -rf android
        npm cache clean --force
        npm install --force

  # Step 2: Generate Android project with Expo
  - name: 'node:20'
    dir: 'rentman-app'
    entrypoint: 'npx'
    args: ['expo', 'prebuild', '--platform', 'android', '--clean']

  # Step 3: Copy keystore into android/app
  - name: 'ubuntu'
    dir: 'rentman-app'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'cp rentman.keystore android/app/'

  # Step 4: Build Android APK - OPTIMIZED VERSION
  - name: 'ghcr.io/cirruslabs/android-sdk:34'
    dir: 'rentman-app/android'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== CONFIGURACIÓN OPTIMIZADA ==="
        
        # Install Node.js 20
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - > /dev/null 2>&1
        apt-get install -y nodejs > /dev/null 2>&1
        
        # Configure Gradle for speed (APPEND to existing gradle.properties)
        echo "" >> gradle.properties
        echo "# Build optimizations" >> gradle.properties
        echo "reactNativeArchitectures=arm64-v8a" >> gradle.properties
        echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError" >> gradle.properties
        echo "org.gradle.daemon=false" >> gradle.properties
        echo "org.gradle.parallel=true" >> gradle.properties
        echo "org.gradle.configureondemand=true" >> gradle.properties
        echo "org.gradle.caching=true" >> gradle.properties
        echo "org.gradle.workers.max=4" >> gradle.properties
        echo "android.enableR8.fullMode=false" >> gradle.properties
        echo "android.enableJetifier=false" >> gradle.properties
        echo "org.gradle.java.installations.auto-download=false" >> gradle.properties
        
        echo "=== INICIANDO BUILD OPTIMIZADO ==="
        chmod +x gradlew
        sed -i 's/\r$//' gradlew
        
        # Build con optimizaciones
        ./gradlew assembleRelease \
          --no-daemon \
          --parallel \
          --max-workers=4 \
          --build-cache \
          --configure-on-demand \
          --stacktrace \
          -x lint \
          -x lintVitalAnalyzeRelease \
          -x lintVitalRelease \
          -x lintVitalReportRelease

  # Step 5: Copy APK to output bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TIMESTAMP=$$(date +%Y%m%d-%H%M%S)
        APK_PATH="/workspace/rentman-app/android/app/build/outputs/apk/release/app-release.apk"
        
        if [ -f "$$APK_PATH" ]; then
          gsutil cp "$$APK_PATH" "gs://rentman-builds/app-release-$${TIMESTAMP}.apk"
          echo "APK uploaded to: gs://rentman-builds/app-release-$${TIMESTAMP}.apk"
          
          gsutil cp "$$APK_PATH" "gs://rentman-builds/app-release-latest.apk"
          echo "Latest APK: gs://rentman-builds/app-release-latest.apk"
        else
          echo "APK not found at $$APK_PATH"
          exit 1
        fi

options:
  logging: GCS_ONLY
  machineType: 'E2_HIGHCPU_32'  # Máquina 4x más potente
  diskSizeGb: 50
  
logsBucket: 'gs://rentman-builds'

timeout: '3600s'
