-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- STRIPE SYNC SCHEMA
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CREATE SCHEMA IF NOT EXISTS stripe;

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE IF NOT EXISTS stripe.accounts (
  _raw_data jsonb NOT NULL,
  first_synced_at timestamp with time zone NOT NULL DEFAULT now(),
  _last_synced_at timestamp with time zone NOT NULL DEFAULT now(),
  _updated_at timestamp with time zone NOT NULL DEFAULT now(),
  business_name text DEFAULT ((_raw_data -> 'business_profile'::text) ->> 'name'::text),
  email text DEFAULT (_raw_data ->> 'email'::text),
  type text DEFAULT (_raw_data ->> 'type'::text),
  charges_enabled boolean DEFAULT ((_raw_data ->> 'charges_enabled'::text))::boolean,
  payouts_enabled boolean DEFAULT ((_raw_data ->> 'payouts_enabled'::text))::boolean,
  details_submitted boolean DEFAULT ((_raw_data ->> 'details_submitted'::text))::boolean,
  country text DEFAULT (_raw_data ->> 'country'::text),
  default_currency text DEFAULT (_raw_data ->> 'default_currency'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  api_key_hashes ARRAY DEFAULT '{}'::text[],
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT accounts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stripe._managed_webhooks (
  id text NOT NULL,
  object text,
  url text NOT NULL,
  enabled_events jsonb NOT NULL,
  description text,
  enabled boolean,
  livemode boolean,
  metadata jsonb,
  secret text NOT NULL,
  status text,
  api_version text,
  created integer,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  last_synced_at timestamp with time zone,
  account_id text NOT NULL,
  CONSTRAINT _managed_webhooks_pkey PRIMARY KEY (id),
  CONSTRAINT fk_managed_webhooks_account FOREIGN KEY (account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe._migrations (
  id integer NOT NULL,
  name character varying NOT NULL UNIQUE,
  hash character varying NOT NULL,
  executed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT _migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stripe._sync_runs (
  _account_id text NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  max_concurrent integer NOT NULL DEFAULT 3,
  error_message text,
  triggered_by text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  closed_at timestamp with time zone,
  CONSTRAINT _sync_runs_pkey PRIMARY KEY (_account_id, started_at),
  CONSTRAINT fk_sync_run_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe._sync_obj_runs (
  _account_id text NOT NULL,
  run_started_at timestamp with time zone NOT NULL,
  object text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'complete'::text, 'error'::text])),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  processed_count integer DEFAULT 0,
  cursor text,
  error_message text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  page_cursor text,
  CONSTRAINT _sync_obj_runs_pkey PRIMARY KEY (_account_id, run_started_at, object),
  CONSTRAINT fk_sync_obj_runs_parent_1 FOREIGN KEY (_account_id, run_started_at) REFERENCES stripe._sync_runs(_account_id, started_at)
);

CREATE TABLE IF NOT EXISTS stripe.active_entitlements (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  feature text DEFAULT (_raw_data ->> 'feature'::text),
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  lookup_key text DEFAULT (_raw_data ->> 'lookup_key'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT active_entitlements_pkey PRIMARY KEY (id),
  CONSTRAINT fk_active_entitlements_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

-- Charges
CREATE TABLE IF NOT EXISTS stripe.charges (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  paid boolean DEFAULT ((_raw_data ->> 'paid'::text))::boolean,
  order_id text DEFAULT (_raw_data ->> 'order'::text), 
  amount bigint DEFAULT ((_raw_data ->> 'amount'::text))::bigint,
  review text DEFAULT (_raw_data ->> 'review'::text),
  source jsonb DEFAULT (_raw_data -> 'source'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  dispute text DEFAULT (_raw_data ->> 'dispute'::text),
  invoice text DEFAULT (_raw_data ->> 'invoice'::text),
  outcome jsonb DEFAULT (_raw_data -> 'outcome'::text),
  refunds jsonb DEFAULT (_raw_data -> 'refunds'::text),
  updated integer DEFAULT ((_raw_data ->> 'updated'::text))::integer,
  captured boolean DEFAULT ((_raw_data ->> 'captured'::text))::boolean,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  refunded boolean DEFAULT ((_raw_data ->> 'refunded'::text))::boolean,
  shipping jsonb DEFAULT (_raw_data -> 'shipping'::text),
  application text DEFAULT (_raw_data ->> 'application'::text),
  description text DEFAULT (_raw_data ->> 'description'::text),
  destination text DEFAULT (_raw_data ->> 'destination'::text),
  failure_code text DEFAULT (_raw_data ->> 'failure_code'::text),
  on_behalf_of text DEFAULT (_raw_data ->> 'on_behalf_of'::text),
  fraud_details jsonb DEFAULT (_raw_data -> 'fraud_details'::text),
  receipt_email text DEFAULT (_raw_data ->> 'receipt_email'::text),
  payment_intent text DEFAULT (_raw_data ->> 'payment_intent'::text),
  receipt_number text DEFAULT (_raw_data ->> 'receipt_number'::text),
  transfer_group text DEFAULT (_raw_data ->> 'transfer_group'::text),
  amount_refunded bigint DEFAULT ((_raw_data ->> 'amount_refunded'::text))::bigint,
  application_fee text DEFAULT (_raw_data ->> 'application_fee'::text),
  failure_message text DEFAULT (_raw_data ->> 'failure_message'::text),
  source_transfer text DEFAULT (_raw_data ->> 'source_transfer'::text),
  balance_transaction text DEFAULT (_raw_data ->> 'balance_transaction'::text),
  statement_descriptor text DEFAULT (_raw_data ->> 'statement_descriptor'::text),
  payment_method_details jsonb DEFAULT (_raw_data -> 'payment_method_details'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT charges_pkey PRIMARY KEY (id),
  CONSTRAINT fk_charges_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.checkout_session_line_items (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  description text DEFAULT (_raw_data ->> 'description'::text),
  price text DEFAULT (_raw_data ->> 'price'::text),
  quantity integer DEFAULT ((_raw_data ->> 'quantity'::text))::integer,
  checkout_session text DEFAULT (_raw_data ->> 'checkout_session'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  amount_discount bigint DEFAULT ((_raw_data ->> 'amount_discount'::text))::bigint,
  amount_subtotal bigint DEFAULT ((_raw_data ->> 'amount_subtotal'::text))::bigint,
  amount_tax bigint DEFAULT ((_raw_data ->> 'amount_tax'::text))::bigint,
  amount_total bigint DEFAULT ((_raw_data ->> 'amount_total'::text))::bigint,
  CONSTRAINT checkout_session_line_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_checkout_session_line_items_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.checkout_sessions (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  adaptive_pricing jsonb DEFAULT (_raw_data -> 'adaptive_pricing'::text),
  after_expiration jsonb DEFAULT (_raw_data -> 'after_expiration'::text),
  allow_promotion_codes boolean DEFAULT ((_raw_data ->> 'allow_promotion_codes'::text))::boolean,
  automatic_tax jsonb DEFAULT (_raw_data -> 'automatic_tax'::text),
  billing_address_collection text DEFAULT (_raw_data ->> 'billing_address_collection'::text),
  cancel_url text DEFAULT (_raw_data ->> 'cancel_url'::text),
  client_reference_id text DEFAULT (_raw_data ->> 'client_reference_id'::text),
  client_secret text DEFAULT (_raw_data ->> 'client_secret'::text),
  collected_information jsonb DEFAULT (_raw_data -> 'collected_information'::text),
  consent jsonb DEFAULT (_raw_data -> 'consent'::text),
  consent_collection jsonb DEFAULT (_raw_data -> 'consent_collection'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  currency_conversion jsonb DEFAULT (_raw_data -> 'currency_conversion'::text),
  custom_fields jsonb DEFAULT (_raw_data -> 'custom_fields'::text),
  custom_text jsonb DEFAULT (_raw_data -> 'custom_text'::text),
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  customer_creation text DEFAULT (_raw_data ->> 'customer_creation'::text),
  customer_details jsonb DEFAULT (_raw_data -> 'customer_details'::text),
  customer_email text DEFAULT (_raw_data ->> 'customer_email'::text),
  discounts jsonb DEFAULT (_raw_data -> 'discounts'::text),
  expires_at integer DEFAULT ((_raw_data ->> 'expires_at'::text))::integer,
  invoice text DEFAULT (_raw_data ->> 'invoice'::text),
  invoice_creation jsonb DEFAULT (_raw_data -> 'invoice_creation'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  locale text DEFAULT (_raw_data ->> 'locale'::text),
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  mode text DEFAULT (_raw_data ->> 'mode'::text),
  optional_items jsonb DEFAULT (_raw_data -> 'optional_items'::text),
  payment_intent text DEFAULT (_raw_data ->> 'payment_intent'::text),
  payment_link text DEFAULT (_raw_data ->> 'payment_link'::text),
  payment_method_collection text DEFAULT (_raw_data ->> 'payment_method_collection'::text),
  payment_method_configuration_details jsonb DEFAULT (_raw_data -> 'payment_method_configuration_details'::text),
  payment_method_options jsonb DEFAULT (_raw_data -> 'payment_method_options'::text),
  payment_method_types jsonb DEFAULT (_raw_data -> 'payment_method_types'::text),
  payment_status text DEFAULT (_raw_data ->> 'payment_status'::text),
  permissions jsonb DEFAULT (_raw_data -> 'permissions'::text),
  phone_number_collection jsonb DEFAULT (_raw_data -> 'phone_number_collection'::text),
  presentment_details jsonb DEFAULT (_raw_data -> 'presentment_details'::text),
  recovered_from text DEFAULT (_raw_data ->> 'recovered_from'::text),
  redirect_on_completion text DEFAULT (_raw_data ->> 'redirect_on_completion'::text),
  return_url text DEFAULT (_raw_data ->> 'return_url'::text),
  saved_payment_method_options jsonb DEFAULT (_raw_data -> 'saved_payment_method_options'::text),
  setup_intent text DEFAULT (_raw_data ->> 'setup_intent'::text),
  shipping_address_collection jsonb DEFAULT (_raw_data -> 'shipping_address_collection'::text),
  shipping_cost jsonb DEFAULT (_raw_data -> 'shipping_cost'::text),
  shipping_details jsonb DEFAULT (_raw_data -> 'shipping_details'::text),
  shipping_options jsonb DEFAULT (_raw_data -> 'shipping_options'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  submit_type text DEFAULT (_raw_data ->> 'submit_type'::text),
  subscription text DEFAULT (_raw_data ->> 'subscription'::text),
  success_url text DEFAULT (_raw_data ->> 'success_url'::text),
  tax_id_collection jsonb DEFAULT (_raw_data -> 'tax_id_collection'::text),
  total_details jsonb DEFAULT (_raw_data -> 'total_details'::text),
  ui_mode text DEFAULT (_raw_data ->> 'ui_mode'::text),
  url text DEFAULT (_raw_data ->> 'url'::text),
  wallet_options jsonb DEFAULT (_raw_data -> 'wallet_options'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  amount_subtotal bigint DEFAULT ((_raw_data ->> 'amount_subtotal'::text))::bigint,
  amount_total bigint DEFAULT ((_raw_data ->> 'amount_total'::text))::bigint,
  CONSTRAINT checkout_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_checkout_sessions_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.coupons (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  object text DEFAULT (_raw_data ->> 'object'::text),
  name text DEFAULT (_raw_data ->> 'name'::text),
  valid boolean DEFAULT ((_raw_data ->> 'valid'::text))::boolean,
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  updated integer DEFAULT ((_raw_data ->> 'updated'::text))::integer,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  duration text DEFAULT (_raw_data ->> 'duration'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  redeem_by integer DEFAULT ((_raw_data ->> 'redeem_by'::text))::integer,
  amount_off bigint DEFAULT ((_raw_data ->> 'amount_off'::text))::bigint,
  percent_off double precision DEFAULT ((_raw_data ->> 'percent_off'::text))::double precision,
  times_redeemed bigint DEFAULT ((_raw_data ->> 'times_redeemed'::text))::bigint,
  max_redemptions bigint DEFAULT ((_raw_data ->> 'max_redemptions'::text))::bigint,
  duration_in_months bigint DEFAULT ((_raw_data ->> 'duration_in_months'::text))::bigint,
  percent_off_precise double precision DEFAULT ((_raw_data ->> 'percent_off_precise'::text))::double precision,
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT coupons_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stripe.credit_notes (
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  customer_balance_transaction text DEFAULT (_raw_data ->> 'customer_balance_transaction'::text),
  discount_amounts jsonb DEFAULT (_raw_data -> 'discount_amounts'::text),
  invoice text DEFAULT (_raw_data ->> 'invoice'::text),
  lines jsonb DEFAULT (_raw_data -> 'lines'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  memo text DEFAULT (_raw_data ->> 'memo'::text),
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  number text DEFAULT (_raw_data ->> 'number'::text),
  pdf text DEFAULT (_raw_data ->> 'pdf'::text),
  reason text DEFAULT (_raw_data ->> 'reason'::text),
  refund text DEFAULT (_raw_data ->> 'refund'::text),
  shipping_cost jsonb DEFAULT (_raw_data -> 'shipping_cost'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  tax_amounts jsonb DEFAULT (_raw_data -> 'tax_amounts'::text),
  type text DEFAULT (_raw_data ->> 'type'::text),
  voided_at text DEFAULT (_raw_data ->> 'voided_at'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  amount bigint DEFAULT ((_raw_data ->> 'amount'::text))::bigint,
  amount_shipping bigint DEFAULT ((_raw_data ->> 'amount_shipping'::text))::bigint,
  discount_amount bigint DEFAULT ((_raw_data ->> 'discount_amount'::text))::bigint,
  out_of_band_amount bigint DEFAULT ((_raw_data ->> 'out_of_band_amount'::text))::bigint,
  subtotal bigint DEFAULT ((_raw_data ->> 'subtotal'::text))::bigint,
  subtotal_excluding_tax bigint DEFAULT ((_raw_data ->> 'subtotal_excluding_tax'::text))::bigint,
  total bigint DEFAULT ((_raw_data ->> 'total'::text))::bigint,
  total_excluding_tax bigint DEFAULT ((_raw_data ->> 'total_excluding_tax'::text))::bigint,
  CONSTRAINT credit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_credit_notes_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.customers (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  address jsonb DEFAULT (_raw_data -> 'address'::text),
  description text DEFAULT (_raw_data ->> 'description'::text),
  email text DEFAULT (_raw_data ->> 'email'::text),
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  name text DEFAULT (_raw_data ->> 'name'::text),
  phone text DEFAULT (_raw_data ->> 'phone'::text),
  shipping jsonb DEFAULT (_raw_data -> 'shipping'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  default_source text DEFAULT (_raw_data ->> 'default_source'::text),
  delinquent boolean DEFAULT ((_raw_data ->> 'delinquent'::text))::boolean,
  discount jsonb DEFAULT (_raw_data -> 'discount'::text),
  invoice_prefix text DEFAULT (_raw_data ->> 'invoice_prefix'::text),
  invoice_settings jsonb DEFAULT (_raw_data -> 'invoice_settings'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  next_invoice_sequence integer DEFAULT ((_raw_data ->> 'next_invoice_sequence'::text))::integer,
  preferred_locales jsonb DEFAULT (_raw_data -> 'preferred_locales'::text),
  tax_exempt text DEFAULT (_raw_data ->> 'tax_exempt'::text),
  deleted boolean DEFAULT ((_raw_data ->> 'deleted'::text))::boolean,
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  balance bigint DEFAULT ((_raw_data ->> 'balance'::text))::bigint,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_customers_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.disputes (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  amount bigint DEFAULT ((_raw_data ->> 'amount'::text))::bigint,
  charge text DEFAULT (_raw_data ->> 'charge'::text),
  reason text DEFAULT (_raw_data ->> 'reason'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  updated integer DEFAULT ((_raw_data ->> 'updated'::text))::integer,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  evidence jsonb DEFAULT (_raw_data -> 'evidence'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  evidence_details jsonb DEFAULT (_raw_data -> 'evidence_details'::text),
  balance_transactions jsonb DEFAULT (_raw_data -> 'balance_transactions'::text),
  is_charge_refundable boolean DEFAULT ((_raw_data ->> 'is_charge_refundable'::text))::boolean,
  payment_intent text DEFAULT (_raw_data ->> 'payment_intent'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT disputes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_disputes_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.early_fraud_warnings (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  actionable boolean DEFAULT ((_raw_data ->> 'actionable'::text))::boolean,
  charge text DEFAULT (_raw_data ->> 'charge'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  fraud_type text DEFAULT (_raw_data ->> 'fraud_type'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  payment_intent text DEFAULT (_raw_data ->> 'payment_intent'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT early_fraud_warnings_pkey PRIMARY KEY (id),
  CONSTRAINT fk_early_fraud_warnings_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.events (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  object text DEFAULT (_raw_data ->> 'object'::text),
  data jsonb DEFAULT (_raw_data -> 'data'::text),
  type text DEFAULT (_raw_data ->> 'type'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  request text DEFAULT (_raw_data ->> 'request'::text),
  updated integer DEFAULT ((_raw_data ->> 'updated'::text))::integer,
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  api_version text DEFAULT (_raw_data ->> 'api_version'::text),
  pending_webhooks bigint DEFAULT ((_raw_data ->> 'pending_webhooks'::text))::bigint,
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stripe.exchange_rates_from_usd (
  _raw_data jsonb NOT NULL,
  _last_synced_at timestamp with time zone,
  _updated_at timestamp with time zone DEFAULT now(),
  _account_id text NOT NULL,
  date date NOT NULL,
  sell_currency text NOT NULL,
  buy_currency_exchange_rates text DEFAULT NULLIF((_raw_data ->> 'buy_currency_exchange_rates'::text), ''::text),
  CONSTRAINT exchange_rates_from_usd_pkey PRIMARY KEY (_account_id, date, sell_currency),
  CONSTRAINT fk_exchange_rates_from_usd_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.features (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  name text DEFAULT (_raw_data ->> 'name'::text),
  lookup_key text DEFAULT (_raw_data ->> 'lookup_key'::text),
  active boolean DEFAULT ((_raw_data ->> 'active'::text))::boolean,
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT features_pkey PRIMARY KEY (id),
  CONSTRAINT fk_features_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.invoices (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  auto_advance boolean DEFAULT ((_raw_data ->> 'auto_advance'::text))::boolean,
  collection_method text DEFAULT (_raw_data ->> 'collection_method'::text),
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  description text DEFAULT (_raw_data ->> 'description'::text),
  hosted_invoice_url text DEFAULT (_raw_data ->> 'hosted_invoice_url'::text),
  lines jsonb DEFAULT (_raw_data -> 'lines'::text),
  period_end integer DEFAULT ((_raw_data ->> 'period_end'::text))::integer,
  period_start integer DEFAULT ((_raw_data ->> 'period_start'::text))::integer,
  status text DEFAULT (_raw_data ->> 'status'::text),
  total bigint DEFAULT ((_raw_data ->> 'total'::text))::bigint,
  account_country text DEFAULT (_raw_data ->> 'account_country'::text),
  account_name text DEFAULT (_raw_data ->> 'account_name'::text),
  account_tax_ids jsonb DEFAULT (_raw_data -> 'account_tax_ids'::text),
  amount_due bigint DEFAULT ((_raw_data ->> 'amount_due'::text))::bigint,
  amount_paid bigint DEFAULT ((_raw_data ->> 'amount_paid'::text))::bigint,
  amount_remaining bigint DEFAULT ((_raw_data ->> 'amount_remaining'::text))::bigint,
  application_fee_amount bigint DEFAULT ((_raw_data ->> 'application_fee_amount'::text))::bigint,
  attempt_count integer DEFAULT ((_raw_data ->> 'attempt_count'::text))::integer,
  attempted boolean DEFAULT ((_raw_data ->> 'attempted'::text))::boolean,
  billing_reason text DEFAULT (_raw_data ->> 'billing_reason'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  custom_fields jsonb DEFAULT (_raw_data -> 'custom_fields'::text),
  customer_address jsonb DEFAULT (_raw_data -> 'customer_address'::text),
  customer_email text DEFAULT (_raw_data ->> 'customer_email'::text),
  customer_name text DEFAULT (_raw_data ->> 'customer_name'::text),
  customer_phone text DEFAULT (_raw_data ->> 'customer_phone'::text),
  customer_shipping jsonb DEFAULT (_raw_data -> 'customer_shipping'::text),
  customer_tax_exempt text DEFAULT (_raw_data ->> 'customer_tax_exempt'::text),
  customer_tax_ids jsonb DEFAULT (_raw_data -> 'customer_tax_ids'::text),
  default_tax_rates jsonb DEFAULT (_raw_data -> 'default_tax_rates'::text),
  discount jsonb DEFAULT (_raw_data -> 'discount'::text),
  discounts jsonb DEFAULT (_raw_data -> 'discounts'::text),
  due_date integer DEFAULT ((_raw_data ->> 'due_date'::text))::integer,
  footer text DEFAULT (_raw_data ->> 'footer'::text),
  invoice_pdf text DEFAULT (_raw_data ->> 'invoice_pdf'::text),
  last_finalization_error jsonb DEFAULT (_raw_data -> 'last_finalization_error'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  next_payment_attempt integer DEFAULT ((_raw_data ->> 'next_payment_attempt'::text))::integer,
  number text DEFAULT (_raw_data ->> 'number'::text),
  paid boolean DEFAULT ((_raw_data ->> 'paid'::text))::boolean,
  payment_settings jsonb DEFAULT (_raw_data -> 'payment_settings'::text),
  receipt_number text DEFAULT (_raw_data ->> 'receipt_number'::text),
  statement_descriptor text DEFAULT (_raw_data ->> 'statement_descriptor'::text),
  status_transitions jsonb DEFAULT (_raw_data -> 'status_transitions'::text),
  total_discount_amounts jsonb DEFAULT (_raw_data -> 'total_discount_amounts'::text),
  total_tax_amounts jsonb DEFAULT (_raw_data -> 'total_tax_amounts'::text),
  transfer_data jsonb DEFAULT (_raw_data -> 'transfer_data'::text),
  webhooks_delivered_at integer DEFAULT ((_raw_data ->> 'webhooks_delivered_at'::text))::integer,
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  subscription text DEFAULT (_raw_data ->> 'subscription'::text),
  payment_intent text DEFAULT (_raw_data ->> 'payment_intent'::text),
  default_payment_method text DEFAULT (_raw_data ->> 'default_payment_method'::text),
  default_source text DEFAULT (_raw_data ->> 'default_source'::text),
  on_behalf_of text DEFAULT (_raw_data ->> 'on_behalf_of'::text),
  charge text DEFAULT (_raw_data ->> 'charge'::text),
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  ending_balance bigint DEFAULT ((_raw_data ->> 'ending_balance'::text))::bigint,
  starting_balance bigint DEFAULT ((_raw_data ->> 'starting_balance'::text))::bigint,
  subtotal bigint DEFAULT ((_raw_data ->> 'subtotal'::text))::bigint,
  tax bigint DEFAULT ((_raw_data ->> 'tax'::text))::bigint,
  post_payment_credit_notes_amount bigint DEFAULT ((_raw_data ->> 'post_payment_credit_notes_amount'::text))::bigint,
  pre_payment_credit_notes_amount bigint DEFAULT ((_raw_data ->> 'pre_payment_credit_notes_amount'::text))::bigint,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT fk_invoices_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.payment_intents (
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  amount_details jsonb DEFAULT (_raw_data -> 'amount_details'::text),
  application text DEFAULT (_raw_data ->> 'application'::text),
  automatic_payment_methods text DEFAULT (_raw_data ->> 'automatic_payment_methods'::text),
  canceled_at integer DEFAULT ((_raw_data ->> 'canceled_at'::text))::integer,
  cancellation_reason text DEFAULT (_raw_data ->> 'cancellation_reason'::text),
  capture_method text DEFAULT (_raw_data ->> 'capture_method'::text),
  client_secret text DEFAULT (_raw_data ->> 'client_secret'::text),
  confirmation_method text DEFAULT (_raw_data ->> 'confirmation_method'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  description text DEFAULT (_raw_data ->> 'description'::text),
  invoice text DEFAULT (_raw_data ->> 'invoice'::text),
  last_payment_error text DEFAULT (_raw_data ->> 'last_payment_error'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  next_action text DEFAULT (_raw_data ->> 'next_action'::text),
  on_behalf_of text DEFAULT (_raw_data ->> 'on_behalf_of'::text),
  payment_method text DEFAULT (_raw_data ->> 'payment_method'::text),
  payment_method_options jsonb DEFAULT (_raw_data -> 'payment_method_options'::text),
  payment_method_types jsonb DEFAULT (_raw_data -> 'payment_method_types'::text),
  processing text DEFAULT (_raw_data ->> 'processing'::text),
  receipt_email text DEFAULT (_raw_data ->> 'receipt_email'::text),
  review text DEFAULT (_raw_data ->> 'review'::text),
  setup_future_usage text DEFAULT (_raw_data ->> 'setup_future_usage'::text),
  shipping jsonb DEFAULT (_raw_data -> 'shipping'::text),
  statement_descriptor text DEFAULT (_raw_data ->> 'statement_descriptor'::text),
  statement_descriptor_suffix text DEFAULT (_raw_data ->> 'statement_descriptor_suffix'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  transfer_data jsonb DEFAULT (_raw_data -> 'transfer_data'::text),
  transfer_group text DEFAULT (_raw_data ->> 'transfer_group'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  amount bigint DEFAULT ((_raw_data ->> 'amount'::text))::bigint,
  amount_capturable bigint DEFAULT ((_raw_data ->> 'amount_capturable'::text))::bigint,
  amount_received bigint DEFAULT ((_raw_data ->> 'amount_received'::text))::bigint,
  application_fee_amount bigint DEFAULT ((_raw_data ->> 'application_fee_amount'::text))::bigint,
  CONSTRAINT payment_intents_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payment_intents_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.payment_methods (
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  type text DEFAULT (_raw_data ->> 'type'::text),
  billing_details jsonb DEFAULT (_raw_data -> 'billing_details'::text),
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  card jsonb DEFAULT (_raw_data -> 'card'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payment_methods_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.payouts (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  object text DEFAULT (_raw_data ->> 'object'::text),
  date text DEFAULT (_raw_data ->> 'date'::text),
  type text DEFAULT (_raw_data ->> 'type'::text),
  amount bigint DEFAULT ((_raw_data ->> 'amount'::text))::bigint,
  method text DEFAULT (_raw_data ->> 'method'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  updated integer DEFAULT ((_raw_data ->> 'updated'::text))::integer,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  automatic boolean DEFAULT ((_raw_data ->> 'automatic'::text))::boolean,
  recipient text DEFAULT (_raw_data ->> 'recipient'::text),
  description text DEFAULT (_raw_data ->> 'description'::text),
  destination text DEFAULT (_raw_data ->> 'destination'::text),
  source_type text DEFAULT (_raw_data ->> 'source_type'::text),
  arrival_date text DEFAULT (_raw_data ->> 'arrival_date'::text),
  bank_account jsonb DEFAULT (_raw_data -> 'bank_account'::text),
  failure_code text DEFAULT (_raw_data ->> 'failure_code'::text),
  transfer_group text DEFAULT (_raw_data ->> 'transfer_group'::text),
  amount_reversed bigint DEFAULT ((_raw_data ->> 'amount_reversed'::text))::bigint,
  failure_message text DEFAULT (_raw_data ->> 'failure_message'::text),
  source_transaction text DEFAULT (_raw_data ->> 'source_transaction'::text),
  balance_transaction text DEFAULT (_raw_data ->> 'balance_transaction'::text),
  statement_descriptor text DEFAULT (_raw_data ->> 'statement_descriptor'::text),
  statement_description text DEFAULT (_raw_data ->> 'statement_description'::text),
  failure_balance_transaction text DEFAULT (_raw_data ->> 'failure_balance_transaction'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT payouts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stripe.plans (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  name text DEFAULT (_raw_data ->> 'name'::text),
  tiers jsonb DEFAULT (_raw_data -> 'tiers'::text),
  active boolean DEFAULT ((_raw_data ->> 'active'::text))::boolean,
  amount bigint DEFAULT ((_raw_data ->> 'amount'::text))::bigint,
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  product text DEFAULT (_raw_data ->> 'product'::text),
  updated integer DEFAULT ((_raw_data ->> 'updated'::text))::integer,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  interval text DEFAULT (_raw_data ->> 'interval'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  nickname text DEFAULT (_raw_data ->> 'nickname'::text),
  tiers_mode text DEFAULT (_raw_data ->> 'tiers_mode'::text),
  usage_type text DEFAULT (_raw_data ->> 'usage_type'::text),
  billing_scheme text DEFAULT (_raw_data ->> 'billing_scheme'::text),
  interval_count bigint DEFAULT ((_raw_data ->> 'interval_count'::text))::bigint,
  aggregate_usage text DEFAULT (_raw_data ->> 'aggregate_usage'::text),
  transform_usage text DEFAULT (_raw_data ->> 'transform_usage'::text),
  trial_period_days bigint DEFAULT ((_raw_data ->> 'trial_period_days'::text))::bigint,
  statement_descriptor text DEFAULT (_raw_data ->> 'statement_descriptor'::text),
  statement_description text DEFAULT (_raw_data ->> 'statement_description'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT plans_pkey PRIMARY KEY (id),
  CONSTRAINT fk_plans_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.prices (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  active boolean DEFAULT ((_raw_data ->> 'active'::text))::boolean,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  nickname text DEFAULT (_raw_data ->> 'nickname'::text),
  recurring jsonb DEFAULT (_raw_data -> 'recurring'::text),
  type text DEFAULT (_raw_data ->> 'type'::text),
  billing_scheme text DEFAULT (_raw_data ->> 'billing_scheme'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  lookup_key text DEFAULT (_raw_data ->> 'lookup_key'::text),
  tiers_mode text DEFAULT (_raw_data ->> 'tiers_mode'::text),
  transform_quantity jsonb DEFAULT (_raw_data -> 'transform_quantity'::text),
  unit_amount_decimal text DEFAULT (_raw_data ->> 'unit_amount_decimal'::text),
  product text DEFAULT (_raw_data ->> 'product'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  unit_amount bigint DEFAULT ((_raw_data ->> 'unit_amount'::text))::bigint,
  CONSTRAINT prices_pkey PRIMARY KEY (id),
  CONSTRAINT fk_prices_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.products (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  active boolean DEFAULT ((_raw_data ->> 'active'::text))::boolean,
  default_price text DEFAULT (_raw_data ->> 'default_price'::text),
  description text DEFAULT (_raw_data ->> 'description'::text),
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  name text DEFAULT (_raw_data ->> 'name'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  images jsonb DEFAULT (_raw_data -> 'images'::text),
  marketing_features jsonb DEFAULT (_raw_data -> 'marketing_features'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  package_dimensions jsonb DEFAULT (_raw_data -> 'package_dimensions'::text),
  shippable boolean DEFAULT ((_raw_data ->> 'shippable'::text))::boolean,
  statement_descriptor text DEFAULT (_raw_data ->> 'statement_descriptor'::text),
  unit_label text DEFAULT (_raw_data ->> 'unit_label'::text),
  updated integer DEFAULT ((_raw_data ->> 'updated'::text))::integer,
  url text DEFAULT (_raw_data ->> 'url'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT fk_products_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.refunds (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  balance_transaction text DEFAULT (_raw_data ->> 'balance_transaction'::text),
  charge text DEFAULT (_raw_data ->> 'charge'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  currency text DEFAULT (_raw_data ->> 'currency'::text),
  destination_details jsonb DEFAULT (_raw_data -> 'destination_details'::text),
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  payment_intent text DEFAULT (_raw_data ->> 'payment_intent'::text),
  reason text DEFAULT (_raw_data ->> 'reason'::text),
  receipt_number text DEFAULT (_raw_data ->> 'receipt_number'::text),
  source_transfer_reversal text DEFAULT (_raw_data ->> 'source_transfer_reversal'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  transfer_reversal text DEFAULT (_raw_data ->> 'transfer_reversal'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  amount bigint DEFAULT ((_raw_data ->> 'amount'::text))::bigint,
  CONSTRAINT refunds_pkey PRIMARY KEY (id),
  CONSTRAINT fk_refunds_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.reviews (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  billing_zip text DEFAULT (_raw_data ->> 'billing_zip'::text),
  charge text DEFAULT (_raw_data ->> 'charge'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  closed_reason text DEFAULT (_raw_data ->> 'closed_reason'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  ip_address text DEFAULT (_raw_data ->> 'ip_address'::text),
  ip_address_location jsonb DEFAULT (_raw_data -> 'ip_address_location'::text),
  open boolean DEFAULT ((_raw_data ->> 'open'::text))::boolean,
  opened_reason text DEFAULT (_raw_data ->> 'opened_reason'::text),
  payment_intent text DEFAULT (_raw_data ->> 'payment_intent'::text),
  reason text DEFAULT (_raw_data ->> 'reason'::text),
  session text DEFAULT (_raw_data ->> 'session'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT fk_reviews_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.setup_intents (
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  description text DEFAULT (_raw_data ->> 'description'::text),
  payment_method text DEFAULT (_raw_data ->> 'payment_method'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  usage text DEFAULT (_raw_data ->> 'usage'::text),
  cancellation_reason text DEFAULT (_raw_data ->> 'cancellation_reason'::text),
  latest_attempt text DEFAULT (_raw_data ->> 'latest_attempt'::text),
  mandate text DEFAULT (_raw_data ->> 'mandate'::text),
  single_use_mandate text DEFAULT (_raw_data ->> 'single_use_mandate'::text),
  on_behalf_of text DEFAULT (_raw_data ->> 'on_behalf_of'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT setup_intents_pkey PRIMARY KEY (id),
  CONSTRAINT fk_setup_intents_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.subscription_item_change_events_v2_beta (
  _raw_data jsonb NOT NULL,
  _last_synced_at timestamp with time zone,
  _updated_at timestamp with time zone DEFAULT now(),
  _account_id text NOT NULL,
  event_timestamp timestamp with time zone NOT NULL,
  event_type text NOT NULL,
  subscription_item_id text NOT NULL,
  currency text DEFAULT NULLIF((_raw_data ->> 'currency'::text), ''::text),
  mrr_change bigint DEFAULT (NULLIF((_raw_data ->> 'mrr_change'::text), ''::text))::bigint,
  quantity_change bigint DEFAULT (NULLIF((_raw_data ->> 'quantity_change'::text), ''::text))::bigint,
  subscription_id text DEFAULT NULLIF((_raw_data ->> 'subscription_id'::text), ''::text),
  customer_id text DEFAULT NULLIF((_raw_data ->> 'customer_id'::text), ''::text),
  price_id text DEFAULT NULLIF((_raw_data ->> 'price_id'::text), ''::text),
  product_id text DEFAULT NULLIF((_raw_data ->> 'product_id'::text), ''::text),
  local_event_timestamp text DEFAULT NULLIF((_raw_data ->> 'local_event_timestamp'::text), ''::text),
  CONSTRAINT subscription_item_change_events_v2_beta_pkey PRIMARY KEY (_account_id, event_timestamp, event_type, subscription_item_id),
  CONSTRAINT fk_subscription_item_change_events_v2_beta_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.subscription_items (
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  billing_thresholds jsonb DEFAULT (_raw_data -> 'billing_thresholds'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  deleted boolean DEFAULT ((_raw_data ->> 'deleted'::text))::boolean,
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  quantity integer DEFAULT ((_raw_data ->> 'quantity'::text))::integer,
  price text DEFAULT (_raw_data ->> 'price'::text),
  subscription text DEFAULT (_raw_data ->> 'subscription'::text),
  tax_rates jsonb DEFAULT (_raw_data -> 'tax_rates'::text),
  current_period_end integer DEFAULT ((_raw_data ->> 'current_period_end'::text))::integer,
  current_period_start integer DEFAULT ((_raw_data ->> 'current_period_start'::text))::integer,
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT subscription_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_subscription_items_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.subscription_schedules (
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  application text DEFAULT (_raw_data ->> 'application'::text),
  canceled_at integer DEFAULT ((_raw_data ->> 'canceled_at'::text))::integer,
  completed_at integer DEFAULT ((_raw_data ->> 'completed_at'::text))::integer,
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  current_phase jsonb DEFAULT (_raw_data -> 'current_phase'::text),
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  default_settings jsonb DEFAULT (_raw_data -> 'default_settings'::text),
  end_behavior text DEFAULT (_raw_data ->> 'end_behavior'::text),
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  phases jsonb DEFAULT (_raw_data -> 'phases'::text),
  released_at integer DEFAULT ((_raw_data ->> 'released_at'::text))::integer,
  released_subscription text DEFAULT (_raw_data ->> 'released_subscription'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  subscription text DEFAULT (_raw_data ->> 'subscription'::text),
  test_clock text DEFAULT (_raw_data ->> 'test_clock'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT subscription_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT fk_subscription_schedules_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.subscriptions (
  _updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  cancel_at_period_end boolean DEFAULT ((_raw_data ->> 'cancel_at_period_end'::text))::boolean,
  current_period_end integer DEFAULT ((_raw_data ->> 'current_period_end'::text))::integer,
  current_period_start integer DEFAULT ((_raw_data ->> 'current_period_start'::text))::integer,
  default_payment_method text DEFAULT (_raw_data ->> 'default_payment_method'::text),
  items jsonb DEFAULT (_raw_data -> 'items'::text),
  metadata jsonb DEFAULT (_raw_data -> 'metadata'::text),
  pending_setup_intent text DEFAULT (_raw_data ->> 'pending_setup_intent'::text),
  pending_update jsonb DEFAULT (_raw_data -> 'pending_update'::text),
  status text DEFAULT (_raw_data ->> 'status'::text),
  application_fee_percent double precision DEFAULT ((_raw_data ->> 'application_fee_percent'::text))::double precision,
  billing_cycle_anchor integer DEFAULT ((_raw_data ->> 'billing_cycle_anchor'::text))::integer,
  billing_thresholds jsonb DEFAULT (_raw_data -> 'billing_thresholds'::text),
  cancel_at integer DEFAULT ((_raw_data ->> 'cancel_at'::text))::integer,
  canceled_at integer DEFAULT ((_raw_data ->> 'canceled_at'::text))::integer,
  collection_method text DEFAULT (_raw_data ->> 'collection_method'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  days_until_due integer DEFAULT ((_raw_data ->> 'days_until_due'::text))::integer,
  default_source text DEFAULT (_raw_data ->> 'default_source'::text),
  default_tax_rates jsonb DEFAULT (_raw_data -> 'default_tax_rates'::text),
  discount jsonb DEFAULT (_raw_data -> 'discount'::text),
  ended_at integer DEFAULT ((_raw_data ->> 'ended_at'::text))::integer,
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  next_pending_invoice_item_invoice integer DEFAULT ((_raw_data ->> 'next_pending_invoice_item_invoice'::text))::integer,
  pause_collection jsonb DEFAULT (_raw_data -> 'pause_collection'::text),
  pending_invoice_item_interval jsonb DEFAULT (_raw_data -> 'pending_invoice_item_interval'::text),
  start_date integer DEFAULT ((_raw_data ->> 'start_date'::text))::integer,
  transfer_data jsonb DEFAULT (_raw_data -> 'transfer_data'::text),
  trial_end jsonb DEFAULT (_raw_data -> 'trial_end'::text),
  trial_start jsonb DEFAULT (_raw_data -> 'trial_start'::text),
  schedule text DEFAULT (_raw_data ->> 'schedule'::text),
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  latest_invoice text DEFAULT (_raw_data ->> 'latest_invoice'::text),
  plan text DEFAULT (_raw_data ->> 'plan'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_subscriptions_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);

CREATE TABLE IF NOT EXISTS stripe.tax_ids (
  _last_synced_at timestamp with time zone,
  _raw_data jsonb,
  _account_id text NOT NULL,
  object text DEFAULT (_raw_data ->> 'object'::text),
  country text DEFAULT (_raw_data ->> 'country'::text),
  customer text DEFAULT (_raw_data ->> 'customer'::text),
  type text DEFAULT (_raw_data ->> 'type'::text),
  value text DEFAULT (_raw_data ->> 'value'::text),
  created integer DEFAULT ((_raw_data ->> 'created'::text))::integer,
  livemode boolean DEFAULT ((_raw_data ->> 'livemode'::text))::boolean,
  owner jsonb DEFAULT (_raw_data -> 'owner'::text),
  id text NOT NULL DEFAULT (_raw_data ->> 'id'::text),
  CONSTRAINT tax_ids_pkey PRIMARY KEY (id),
  CONSTRAINT fk_tax_ids_account FOREIGN KEY (_account_id) REFERENCES stripe.accounts(id)
);
